# Generated by Django 4.0.1 on 2022-02-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0007_category_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='movies',
        ),
    ]
