# Generated by Django 4.0.1 on 2022-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0008_remove_category_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='gaflix.Movie'),
        ),
    ]
