# Generated by Django 4.0.1 on 2022-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0009_category_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['birth_date']},
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[['male', 'Muž'], ['female', 'Žena'], ['other', 'Jiné']], default='other', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(blank=True, to='gaflix.Movie'),
        ),
    ]
