# Generated by Django 4.0.1 on 2022-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0010_alter_actor_options_person_sex_alter_category_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[['male', 'Muž'], ['female', 'Žena'], ['other', 'Jiné']], default='male', max_length=64),
        ),
    ]
