# Generated by Django 4.0.1 on 2022-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0011_movie_thumbnail_alter_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
