# Generated by Django 4.0.1 on 2022-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0013_remove_movie_thumbnail_remove_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Nahled'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Trailer'),
        ),
    ]
